### ISSUE TITLE
Unable to execute `install.ps1` on Windows 11

### ISSUE THREAD

**Issue by KukicVidan** [catppuccin/windows-files#17]
iex : A parameter cannot be found that matches parameter name 'AsHashtable'.
At line:1 char:109
+ ... ps://github.com/catppuccin/windows-files/raw/main/install.ps1 } | iex
+                                                                       ~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by sgoudham** [comment]
Hey 👋,

Did you get this error while running the command under [powershell 7](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.4#installing-powershell-7)? 

I believe you can check the version of PS by typing in `$PSVERSIONTABLE` but I don't have access to a windows machine at the moment so that may be incorrect or outdated.

**Comment by sluhtie** [comment]
> iex : A parameter cannot be found that matches parameter name 'AsHashtable'. At line:1 char:109
>       * CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
>       * FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

I had this Issue aswell at first but then noticed I haven't used PS7. Updating was the solution for me.
